### ISSUE TITLE
Erro na instalação

### ISSUE THREAD

**Issue by equipe360rj** [MestreLion/videoke#1]
Boa noite. Tentei instalar o videoke no Lubuntu 22.04 mas apresenta erro em um arquivo. Poderia me ajudar a solucionar? Segue o erro:

pc@pc:~/.local/share$ videoke/install.sh
Lendo listas de pacotes... Pronto
Construindo árvore de dependências... Pronto
Lendo informação de estado... Pronto
python3-pygame is already the newest version (2.1.2+dfsg-3).
0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 220 não atualizados.
xdg-icon-resource: file './videoke*.png' does not exist
error: line 39, status 2: xdg-icon-resource install --noupdate --novendor --size "$size" "$icon" "videoke"

**Comment by MestreLion** [comment]
Corrigi o erro, tente baixar e instalar de novo, e obrigado!

(PS: mudei também o nome do branch principal, então melhor refazer o clone do repositório)

**Comment by equipe360rj** [comment]
Agora aparece a seguinte mensagem:

pc@pc:~/.local/share$ videoke/install.sh
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
error: line 18, status 1: pip3 install --user --upgrade -r requirements.txt

**Comment by MestreLion** [comment]
@linuxarcade , pronto, agora sim... atualize e veja se tá ok

**Comment by MestreLion** [comment]
(PS: ambos os bugs ocorreram pq vc está executando `install.sh` _fora_ do repositório. Várias ferramentas (como make e git) exigem serem executadas _dentro_ da pasta:
```
git clone .../xxx
cd xxx
...
```

**Comment by libiojunior** [comment]
instalei o linuxmint ele fez o clone antes ja tinha isntalado python e as bibliotecas  e ainda acontece os erro abaixo

junior@junior-desktop:~$ cd ~/.local/share
junior@junior-desktop:~/.local/share$ videoke/install.sh
Requirement already satisfied: ffpyplayer in /home/junior/.local/lib/python3.10/site-packages (from -r /home/junior/.local/share/videoke/requirements.txt (line 1)) (4.5.1)
Requirement already satisfied: pygame in /home/junior/.local/lib/python3.10/site-packages (from -r /home/junior/.local/share/videoke/requirements.txt (line 2)) (2.5.2)
xdg-desktop-menu: file 'videoke.desktop' does not exist
error: line 36, status 2: xdg-desktop-menu install --novendor "$desktop"
junior@junior-desktop:~/.local/share$ ^C
junior@junior-desktop:~/.local/share$ xdg-desktop-menu install --novendor "$desktop"
xdg-desktop-menu: file '' does not exist
junior@junior-desktop:~/.local/share$ xdg-desktop-menu install --novendor
xdg-desktop-menu: desktop-file argument missing
Try 'xdg-desktop-menu --help' for more information.
junior@junior-desktop:~/.local/share$ videoke/install.sh
Requirement already satisfied: ffpyplayer in /home/junior/.local/lib/python3.10/site-packages (from -r /home/junior/.local/share/videoke/requirements.txt (line 1)) (4.5.1)
Requirement already satisfied: pygame in /home/junior/.local/lib/python3.10/site-packages (from -r /home/junior/.local/share/videoke/requirements.txt (line 2)) (2.5.2)
xdg-desktop-menu: file 'videoke.desktop' does not exist
error: line 36, status 2: xdg-desktop-menu install --novendor "$desktop"
junior@junior-desktop:~/.local/share$

**Comment by MestreLion** [comment]
> instalei o linuxmint ele fez o clone antes ja tinha isntalado python e as bibliotecas e ainda acontece os erro abaixo

@libiojunior Tenta com essa nova atualização que fiz agora
