### ISSUE TITLE
Karaoke

### ISSUE THREAD

**Issue by libiojunior** [MestreLion/videoke#2]
Ola, tem ate um amigo ai que conheço esta tentando tambem e nao ta tendo sucesso, ele ta testand via linux , vou instalar linux tbm pra testar , queria so ver como é a interface e como ele funciona , Obrigado

**Comment by MestreLion** [comment]
Ele também funciona no Windows, desde que você tenha instalado Python e as bibliotecas Pygame e ffpyplayer (e você pode baixar ambas com `pip`)
